iTjuana/itj-library

- README.md
- package-lock.json
- package.json
- src/pages/_app.tsx
Adding free and react fontawesome dependencies
> Add fontawesome

- .env.example
- src/env.mjs
- No tests required
#26 
- Updated .env.example file to describe the properties the .env file should contain.
- Updated the validation on env.mjs to search the correct properties.
N/A
N/A
- If deploying without the correct properties an error should be displayed
> :sparkles: Update env example for providers to use

- prisma/schema.prisma
Added Prisma model for User, Inventory and Transaction. 
- Added to PlanetScale database three new tables
> :sparkles: Add Prisma Schema

- prisma/schema.prisma
Create new table for itj_library on schema.prisma
Join to db, use planet scale to verify tables exists
#30
> Feature database

- src/components/book.tsx
- src/pages/_app.tsx
- src/pages/catalog.tsx
- src/pages/index.tsx
- Move layout to _app.tsx.
- Move Book component to another file.
- Change API endpoint so that the return json is smaller.
Reduce time to load /catalog
Using one typescript ignore and eslint ignore for the getServerSideProps function in catalog.
- #46
> Feature move layout

- src/components/layout.tsx
- src/components/navbar.tsx
Following the Figma design, the navbar component was created and according with the latest changes. Also pages variable will be used in upcoming features related to navbar component.  
Run the UI and go to index page.
- #19 
N/A
> :sparkles: Add Navbar component

- src/components/button.tsx
- src/components/data-table.tsx
- src/components/dropdown.tsx
- src/components/input.tsx
- src/components/table.tsx
- src/pages/manage.tsx
Following the Figma design, the admin page was created. It needs data table component, also is it necessary to use server side props or is it enough to load after page loads.
Run the UI and go to the admin page.
- Closes #36 
N/A
> :sparkles: Admin page with components

- src/pages/account.tsx
Following the Figma design, the account page was created. It needs a functional table of activity.
Run the UI and go to the account page.
- Closes #37 
N/A
> :sparkles: Add account page

- src/components/navbar.tsx
- src/components/navlink.tsx
The NavbarLink component was created by the navbar component logic to create a reusable component.
Run the UI and go to index page.
- #19 
N/A
> Feature navblink component

- package-lock.json
- package.json
- src/components/data-table.tsx
- src/components/dropdown.tsx
- src/components/input.tsx
- src/components/table.tsx
- src/pages/account.tsx
- src/pages/catalog.tsx
- src/pages/manage.tsx
- src/server/routers/_app.ts
Reverts iTjuana/itj-library#58
> Revert "Feature 50 fetch client and trpc catalog"

- src/pages/account.tsx
Migrate Button component from vanilla component to Materials UI library.
Add Modal funciona
Run the UI and go to account page, click the button and a modal should appear.
- #56
> Add Button and Modal from MUI to Account page

- prisma/schema.prisma
- Structure 
- Optimization
- The books table was added to add those that do not appear in the API
- The examples table was deleted
- Reference warnings with @@index were corrected
- Upgrade of data base
> :zap: Book table is added

- src/components/layout.tsx
Wrap Logo on Navbar with Link.
Run the UI and go to any page, then click on the logo.
- Closes #63 
N/A
> ✨ Logo on Navbar wrapped with Link

- package-lock.json
- package.json
- src/pages/_app.tsx
Install Vercel Analytics and add component to _app.tsx file.
Wait for deployment, go to Vercel and go to Analytics tab.
- Closes #65 
N/A
> :sparkles: Vercel Analytics Setup

- prisma/schema.prisma
- src/components/book.tsx
- src/pages/catalog.tsx
- src/server/api/routers/books.ts
Migrate from external API for getting data, to our own database with trpc books router.
Added a new public procedure to the books router to find books by an array of ids.
Update Inventory schema to require bookId and book.
1. Run the UI and go to catalog
2. Then wait for data to load
3. Finally, use Pagination to change page
- Closes #45 
- Added Pagination functionality to Catalog page.
> Add Pagination Functionality on Catalog

- src/components/layout.tsx
- src/components/navbar.tsx
- src/components/navlink.tsx
Following the Figma design, the hamburger component was created and according with the latest changes. 
Run the UI and go to index page.
- #19 
N/A
> :shirt: Add hamburger component

- prisma/schema.prisma
- src/pages/catalog.tsx
- src/pages/index.tsx
- src/server/api/routers/books.ts
- src/server/api/routers/inventory.ts
This change allows us to optimize the database, we changed the Int data type in the "Book" table to language and number_of_pages, in the "Inventary" table we modified the status, format and condition.
Also change APIs to work with these changes.
Work with the API and see types of books and inventory.
- #75 
- Use enum on db
> :hammer: Make changes to DB and API to use enums

- src/pages/manage.tsx
Description of the Change
Using MUI materials in manage page (Buttons)
Verification Process
Manage page is working with the buttons interface changed to MUI Materials
Applicable Issues
- #56 
Release Notes
N/A
> Manage page to MUI Materials

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/pages/api/trpc/[trpc].ts
- src/pages/index.tsx
- src/server/api/routers/books.ts
- src/server/api/trpc.ts
- utils/logger.ts
Description of the Change
Added the integration to Axiom so that logs are sent to the tool and included a custom logger for more customized logs according to the project needs.
Possible Drawbacks
- Refactoring APIs to add custom logger.
Verification Process
- Example of custom logs in Axiom
> :sparkles: Custom logger to Axiom

- .vscode/settings.json
- package-lock.json
- src/components/carousel.tsx
- src/components/filterSelect.tsx
- src/components/filters.tsx
- src/pages/catalog.tsx
- src/pages/index.tsx
- src/server/api/routers/inventory.ts
Search functionality for filters bar
Created Filters and FiltersSelect components to refactor the catalog screen
Added search by title at inventory
We can create a spike to see more filters with this input in tRPC
Go to the catalog and search for a book by his name
> Added search functionality and update components

- src/pages/book/[book].tsx
- src/pages/catalog.tsx
- src/pages/index.tsx
- src/pages/manage.tsx
- src/server/api/routers/inventory.ts
- src/server/api/routers/users.ts
Some lint, some loaders, some changes to api
1. Run the UI
2. Go through the website
N/A
> 🔨 General enhancement for demo #1

- src/components/filters.tsx
- src/pages/catalog.tsx
- src/server/api/routers/inventory.ts
Added debounce effect at filters component
Improve performance by making only one request for search instead of one request for every letter
If the time is too much, we can reduce the time for the effect
Go to catalog and search for a book
> Add filter functionality to inventory page

- src/components/book.tsx
- src/components/filters.tsx
- src/pages/catalog.tsx
Refactor catalog screen styles
Go to /catalog and see the new UI
- Closes #99 
Update catalog screen
> Refactor catalog screen 🎠 

- src/components/carousel.tsx
- src/components/filterSelect.tsx
- src/components/filters.tsx
- src/components/layout.tsx
- src/components/navbar.tsx
- src/components/navlink.tsx
- src/components/transactions.tsx
- src/pages/book/[book].tsx
- src/pages/catalog.tsx
- src/pages/index.tsx
Update responsive design at home, catalog and book by id
See the screens in a responsive mode
- Closes #104
Responsive design
> Responsive design 🎠 

- utils/session.ts
Bugfix of 403 for getting admin only query, instead using session
> Bugfix use session for getting userId

- src/hooks/useTransaction.ts
- src/server/api/routers/inventory.ts
- src/server/api/routers/transaction.ts
A normal user only can update transaction or inventory's status
> Create limited update transaction and inventory

- src/server/api/routers/transaction.ts
didn't update admin procedure to private procedure x.x
>  Create limited update transaction

- src/components/toReviewTable.tsx
- src/components/transactions.tsx
- src/hooks/useTransaction.ts
- src/pages/account.tsx
- src/pages/book/[book].tsx
- src/pages/index.tsx
- src/pages/manage.tsx
Added Optimistic UI to some features on the app like borrow a book, review book and return book
This will allow our users to see in real time the change of the table statuses.
- Borrow a book and then return it
- For management, review a book
Closes #120
> Added optimistic UI and updated some styles
